#!/bin/bash
./dev Main
while [ true ]; do
  old=$(stat -c %y Main.elm)
  while [ true ]; do
    new=$(stat -c %y Main.elm)
    if [ "$old" != "$new" ]; then
      ./dev Main
      old="$new"
      echo "updated: " `date`
      break
    else
      sleep 4
    fi
  done
done
