#!/bin/bash
RUNNING="./monitor.tmp"

touch "$RUNNING"

MOD="$1"
FILE="src/$1"
DEP="src/$2"

./format-build "$FILE"
old=$(./hash "$FILE.elm")
while [ -f "$RUNNING" ]; do
  new=$(./hash "$FILE.elm")
  if [ "$old" != "$new" ]; then
    ./format-build "$FILE"
    old="$new"
    echo "updated $MOD:" `date`
  else
    sleep 4
  fi
done
echo "stopped monitor on $MOD."
