#!/bin/bash
RUNNING="./monitor.lock"

touch "$RUNNING"

MOD="$1"
FILE="src/$1.elm"
DEP="src/$2"

./format-build "$MOD"
old=$(./hash "$FILE")
while [ true ]; do
  new=$(./hash "$FILE")
  if [ "$old" != "$new" ]; then
    ./format-build "$MOD"
    old="$new"
    echo "updated $MOD:" `date`
    if [ "$MOD" != "Main" ]; then
      ./build Main
    fi
  elif [ -f "$RUNNING" ]; then
    sleep 4
  else
    break
  fi
done
echo "stopped monitor on $MOD."
