#!/bin/bash
./format-build Theme
./format-build Main
oldTheme=$(stat -c %y Theme.elm)
oldMain=$(stat -c %y Main.elm)
while [ true ]; do
  newTheme=$(stat -c %y Theme.elm)
  if [ "$oldTheme" != "$newTheme" ]; then
    ./format-build Theme && ./build Main
    oldTheme="$newTheme"
    echo "updated Theme: " `date`
    break
  fi
  newMain=$(stat -c %y Main.elm)
  if [ "$oldMain" != "$newMain" ]; then
    ./format-build Main
    oldMain="$newMain"
    echo "updated Main: " `date`
    break
  else
    sleep 4
  fi
done
