#!/bin/bash
RUNNING="./monitor.lock"

touch "$RUNNING"

if [ ! -d dist/index.html ]; then
  cp src/index.html dist/index.html
fi

old=$(./hash src/index.html)
while [ true ]; do
  new=$(./hash src/index.html)
  if [ "$old" != "$new" ]; then
    cp src/index.html dist/index.html
    old="$new"
    echo "updated index.html"
  elif [ -f "$RUNNING" ]; then
    sleep 4
  else
    break
  fi
done
echo "stopped monitor on index.html"
